# Generated by Django 5.2.1 on 2025-05-26 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) 123-45-67', regex='^\\+375 \\(?(17|25|29|33|44)\\)? \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
