# Generated by Django 5.2.1 on 2025-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_age_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('summary', models.CharField(max_length=300, verbose_name='Краткое содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Картинка')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
