# Generated by Django 5.2.1 on 2025-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remedy_remove_medication_category_medication_remedy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
