# Generated by Django 5.2.1 on 2025-05-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_archivedpromocode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedpromocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
