# Generated by Django 5.2.1 on 2025-05-26 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Фото')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание выполняемых работ')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) 123-45-67', regex='^\\+375 \\(?(17|25|29|33|44)\\)? \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
