# Generated by Django 5.2.1 on 2025-05-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лечащего средства')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
        ),
        migrations.RemoveField(
            model_name='medication',
            name='category',
        ),
        migrations.AddField(
            model_name='medication',
            name='remedy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.remedy', verbose_name='Лечащее средство'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MedicationCategory',
        ),
    ]
