# Generated by Django 5.2.1 on 2025-05-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sale_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Промокод')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка')),
                ('expired_at', models.DateTimeField(verbose_name='Дата истечения')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивации')),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Действует до'),
        ),
    ]
